

// // src/components/ResultsTable.jsx
// // // ResultsTable.jsx — Professional UI with candidate name = resume filename
// import React from "react";
// import { DataGrid } from "@mui/x-data-grid";
// import { Box, Button, Card, CardHeader, CardContent } from "@mui/material";
// import { saveAs } from "file-saver";
// export default function ResultsTable({ rows, jdParsed, email }) {
//   const cols = [
//     { field: "Name", headerName: "Candidate", flex: 1 },
//     { field: "Strengths", headerName: "Strengths", flex: 1.2 },
//     { field: "Missing Primary", headerName: "Missing Primary", flex: 1 },
//     { field: "Missing Secondary", headerName: "Missing Secondary", flex: 1 },
//     { field: "Years of Experience", headerName: "Yrs Exp", width: 90 },
//     { field: "Primary Score", headerName: "Primary %", width: 100 },
//     { field: "Secondary Score", headerName: "Secondary %", width: 110 },
//     { field: "Overall Score", headerName: "Overall %", width: 100 },
//     { field: "Status", headerName: "Status", width: 110 },
//   ];

//   const exportCSV = () => {
//     const csvRows = [];
//     csvRows.push("Generated by," + email);

//     // Candidate headers
//     csvRows.push(cols.map((c) => c.headerName).join(","));

//     // Candidate data
//     rows.forEach((r) => {
//       csvRows.push(
//         cols
//           .map((c) => `"${String(r[c.field] || "").replace(/,/g, " ")}"`)
//           .join(",")
//       );
//     });

//     // Add 2 empty rows
//     csvRows.push("");
//     csvRows.push("");

//     // Add primary skills row
//     if (jdParsed?.primarySkills?.length) {
//       csvRows.push(`Primary:,` + `${jdParsed.primarySkills.join(" ")}`);
//     }

//     // Add 1 empty row
//     csvRows.push("");

//     // Add secondary + other in the same row
//     const secondary = jdParsed?.secondarySkills?.join("  ") || "";
//     const other = jdParsed?.otherSkills?.join("  ") || "";
//     if (secondary || other) {
//       csvRows.push(`Secondary:,` + `${secondary}`);
//       csvRows.push(`Other:,` + `${other}`);
//     }

//     const csvContent = csvRows.join("\n");
//     // saveAs(new Blob([csvContent], { type: "text/csv" }), "results.csv");
//     // -----------------------------------------------------
//   // ✔️ Create dynamic file name: client_role_datetime.csv
//   // -----------------------------------------------------
//   const client = jdParsed?.client || "Client";
//   const role = jdParsed?.role || "Role";

//   const now = new Date();
//   const dt =
//     now.getFullYear().toString() +
//     String(now.getMonth() + 1).padStart(2, "0") +
//     String(now.getDate()).padStart(2, "0") +
//     "_" +
//     String(now.getHours()).padStart(2, "0") +
//     String(now.getMinutes()).padStart(2, "0");
//     // String(now.getSeconds()).padStart(2, "0");

//   const safeClient = client.replace(/[^a-zA-Z0-9-_]/g, "");
//   const safeRole = role.replace(/[^a-zA-Z0-9-_]/g, "");
//   const filename = `${safeClient}_${safeRole}_${dt}.csv`;

//   saveAs(new Blob([csvContent], { type: "text/csv" }), filename);
//   };

//   return (
//     <Card sx={{ borderRadius: 2, mt: 3 }}>
//       <CardHeader title="Candidate Match Results" sx={{ background: "#f8f9fb" }} />
//       <CardContent>
//         <Box sx={{ mb: 2 }}>
//           <Button variant="outlined" onClick={exportCSV}>
//             Export CSV
//           </Button>
//         </Box>

//         <Box sx={{ height: 420 }}>
//           <DataGrid
//             rows={rows.map((r, i) => ({ id: i, ...r }))}
//             columns={cols}
//             pageSize={10}
//           />
//         </Box>
//       </CardContent>
//     </Card>
//   );
// }

// src/components/ResultsTable.jsx
// src/components/ResultsTable.jsx
import React, { useState } from "react";
import {
  Box,
  Button,
  Card,
  CardHeader,
  CardContent,
  Stack,
} from "@mui/material";
import { DataGrid } from "@mui/x-data-grid";
import { saveAs } from "file-saver";
import ResumeUploader from "./ResumeUploader";
import { analyzeResumes } from "../api/api";
import Backdrop from "@mui/material/Backdrop";
import CircularProgress from "@mui/material/CircularProgress";

export default function ResultsTable({
  rows,
  setRows,
  jdText,
  jdParsed,
  client,
  role,
  email,
}) {
  const [status, setStatus] = useState(""); // ✅ Add this

  const [files, setFiles] = useState([]);
  const [loading, setLoading] = useState(false);

  const hasFiles = rows.length > 0;
  const hasAnalyzed = rows.some((r) => r.Status);

  // ================= TABLE COLUMNS =================
  const cols = [
    {
      field: "Name",
      headerName: "Candidate",
      flex: 1.5,
      renderCell: (params) => (
        <Box
          sx={{
            overflow: "hidden",
            textOverflow: "ellipsis",
            whiteSpace: "nowrap",
            width: "100%",
          }}
          title={params.value}
        >
          {params.value}
        </Box>
      ),
    },
    { field: "Strengths", headerName: "Strengths", flex: 1.2 },
    { field: "Missing Primary", headerName: "Missing Primary", flex: 1 },
    { field: "Missing Secondary", headerName: "Missing Secondary", flex: 1 },
    { field: "Years of Experience", headerName: "Yrs Exp", width: 90 },
    { field: "Primary Score", headerName: "Primary %", width: 100 },
    { field: "Secondary Score", headerName: "Secondary %", width: 110 },
    { field: "Overall Score", headerName: "Overall %", width: 100 },
    { field: "Status", headerName: "Status", width: 110 },
  ];

  // ================= ANALYZE =================
  // const analyze = async () => {
  //   if (!jdText || files.length === 0) return;

  //   setLoading(true);
  //   try {
  //     const { results } = await analyzeResumes(jdText, files, client, role);

  //     const merged = results.map((r, i) => ({
  //       Name: files[i]?.name || `Candidate ${i + 1}`,
  //       Strengths: r.Strengths || "",
  //       "Missing Primary": r["Missing Primary"] || "",
  //       "Missing Secondary": r["Missing Secondary"] || "",
  //       "Years of Experience": r["Years of Experience"] || "",
  //       "Primary Score": r["Primary Score"] || "",
  //       "Secondary Score": r["Secondary Score"] || "",
  //       "Overall Score": r["Overall Score"] || "",
  //       Status: r.Status || "",
  //     }));

  //     setRows(merged);
  //   } catch (err) {
  //     console.error(err);
  //     alert("Analysis failed");
  //   }
  //   setLoading(false);
  // };
const analyze = async () => {
  if (!jdText || files.length === 0) return;

  setLoading(true); // show loader
  setRows([]);

  try {
    const { results } = await analyzeResumes(jdText, files, client, role);

    const merged = results.map((r, i) => ({
      Name: r.Name || `Candidate ${i + 1}`,
      Strengths: r.Strengths || "",
      "Missing Primary": r["Missing Primary"] || "",
      "Missing Secondary": r["Missing Secondary"] || "",
      "Years of Experience": r["Years of Experience"] || "",
      "Primary Score": r["Primary Score"] || "",
      "Secondary Score": r["Secondary Score"] || "",
      "Overall Score": r["Overall Score"] || "",
      Status: r.Status || "",
    }));

    setRows(merged);
  } catch (err) {
    console.error(err);
    alert("Analysis failed");
  }

  setLoading(false); // hide loader
};



  // ================= EXPORT CSV =================
  const exportCSV = () => {
    const csvRows = [];
    csvRows.push("Generated by," + email);
    csvRows.push(cols.map((c) => c.headerName).join(","));

    rows.forEach((r) => {
      csvRows.push(
        cols
          .map((c) => `"${String(r[c.field] || "").replace(/,/g, " ")}"`)
          .join(",")
      );
    });

    csvRows.push("", "");

    if (jdParsed?.primarySkills?.length) {
      csvRows.push(`Primary:,${jdParsed.primarySkills.join(" ")}`);
    }

    csvRows.push("");

    if (jdParsed?.secondarySkills?.length) {
      csvRows.push(`Secondary:,${jdParsed.secondarySkills.join(" ")}`);
    }

    if (jdParsed?.otherSkills?.length) {
      csvRows.push(`Other:,${jdParsed.otherSkills.join(" ")}`);
    }

    const clientName = jdParsed?.client || "Client";
    const roleName = jdParsed?.role || "Role";
    const now = new Date();
    const dt =
      now.getFullYear().toString() +
      String(now.getMonth() + 1).padStart(2, "0") +
      String(now.getDate()).padStart(2, "0") +
      "_" +
      String(now.getHours()).padStart(2, "0") +
      String(now.getMinutes()).padStart(2, "0");

    const filename = `${clientName}_${roleName}_${dt}.csv`.replace(
      /[^a-zA-Z0-9-_]/g,
      ""
    );

    saveAs(new Blob([csvRows.join("\n")], { type: "text/csv" }), filename);
  };

  return (
    <Card sx={{ borderRadius: 2 }}>
      {/* ================= HEADING ================= */}
      <CardHeader
        title="Screening Results"
        sx={{ background: "#f8f9fb" }}
      />

      <CardContent>
        {/* ================= ACTION BAR ================= */}
        <Stack
          direction="row"
          justifyContent="space-between"
          alignItems="center"
          sx={{ mb: 2 }}
        >
          {/* LEFT */}
          <Stack direction="row" spacing={2}>
            <ResumeUploader
              setFiles={setFiles}
              onResults={setRows}
            />

            <Button
              variant="contained"
              disabled={!hasFiles || loading}
              onClick={analyze}
            >
              Analyze Resumes
            </Button>
          </Stack>

          {/* RIGHT */}
          <Button
            variant="outlined"
            disabled={!hasAnalyzed}
            onClick={exportCSV}
          >
            Export CSV
          </Button>
        </Stack>

        {/* ================= TABLE ================= */}
        <Box sx={{ height: 420 }}>
          <DataGrid
            rows={rows.map((r, i) => ({ id: i, ...r }))}
            columns={cols}
            pageSize={10}
            loading={loading}
          />
        </Box>
      </CardContent>
      {loading && (
        <Backdrop
          open={true}
          sx={{ color: "#fff", zIndex: (theme) => theme.zIndex.drawer + 1 }}
        >
          <CircularProgress color="inherit" />
        </Backdrop>
      )}
    </Card>
  );
}

